apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  namespace: ${PROJECT_GROUP}
  labels:
    app: ${PROJECT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers:
        - image: ${DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${PROJECT_VERSION}
          imagePullPolicy: Always
          name: ${PROJECT_NAME}
          ports:
            - containerPort: 3000
              name: tcp3000
              protocol: TCP
      restartPolicy: Always
status: {}
