from: ${DOCKER_REGISTRY}/${RUNNER_NEXTJS}
image: ${DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${PROJECT_VERSION}
env:
  NODE_ENV: production
add:
  ./: /var/services
entrypoint:
  - ./entrypoint.sh