apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ${PROJECT_NAME}
  namespace: ${PROJECT_GROUP}
  ownerReferences:
    - apiVersion: apps/v1beta2
      kind: Deployment
      name: ${PROJECT_NAME}
      uid: ${DEPLOYMENT_UID}
spec:
  ports:
    - name: tcp3000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: ${PROJECT_NAME}
